=== miguelangel-jg/XML_Ejercicios/XML/Casas/casa.dtd
<!ELEMENT casa (direccion, habitaciones, jardin)>
<!ELEMENT direccion (calle, ciudad, provincia, pais)>
<!ELEMENT calle (#PCDATA)>
<!ATTLIST calle tipo (principal|secundaria) "principal">
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ATTLIST pais codigo CDATA #REQUIRED>
<!ELEMENT habitaciones (habitacion+)>
<!ELEMENT habitacion (nombre, dimensiones, muebles)>
<!ATTLIST habitacion tipo (dormitorio|salon) #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dimensiones EMPTY>
<!ATTLIST dimensiones
    largo CDATA #REQUIRED
    ancho CDATA #REQUIRED
    altura CDATA #REQUIRED>
<!ELEMENT muebles (mueble+)>
<!ELEMENT mueble EMPTY>
<!ATTLIST mueble
    tipo CDATA #REQUIRED
    material CDATA #REQUIRED>
<!ELEMENT jardin (tipo, dimensiones, elementos)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT elementos (elemento+)>
<!ELEMENT elemento EMPTY>
<!ATTLIST elemento
    tipo CDATA #REQUIRED
    forma CDATA #IMPLIED>

=== miguelangel-jg/XML_Ejercicios/XML/Casas/casas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casa SYSTEM "casa.dtd">
<casa>
    <direccion>
        <calle tipo="principal">Paseo de Consolacion</calle>
        <ciudad>Utrera</ciudad>
        <provincia>Sevilla</provincia>
        <pais codigo="esp">Espa√±a</pais>
    </direccion>
    <habitaciones>
        <habitacion tipo="dormitorio">
            <nombre>Habitacion principal</nombre>
            <dimensiones largo="5" ancho="4" altura="3"/>
            <muebles>
                <mueble tipo="cama" material="madera"></mueble>
                <mueble tipo="armario" material="metalico"></mueble>
            </muebles>
        </habitacion>

        <habitacion tipo="salon">
            <nombre>Salon comedor</nombre>
            <dimensiones largo="8" ancho="6" altura="3"/>
            <muebles>
                <mueble tipo="sofa" material="cuero"></mueble>
                <mueble tipo="mesa" material="madera"></mueble>
                <mueble tipo="televisor" material="plastico"></mueble>
            </muebles>
        </habitacion>
    </habitaciones>
    <jardin>
        <tipo>Delantero</tipo>
        <dimensiones largo="20" ancho="20" altura=""/>
        <elementos>
            <elemento tipo="cesped"></elemento>
            <elemento tipo="piscina" forma="rectangular"></elemento>
        </elementos>
    </jardin>

</casa>
