=== miguelangel-jg/XML_Ejercicios/XML/deportistas.dtd
<!ELEMENT deportistas (deportista+)>
<!ELEMENT deportista (deporte)>
<!ELEMENT deporte (nombreDeporte,nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nombreDeporte (#PCDATA)>

=== miguelangel-jg/XML_Ejercicios/XML/deportistas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas SYSTEM "deportistas.dtd">
<deportistas>
    <deportista>
        <deporte> 
            <nombreDeporte>Atletismo</nombreDeporte>
            <nombre>Jesse Owens</nombre>
        </deporte>        
    </deportista>
    <deportista>
        <deporte>
            <nombreDeporte>Natacion</nombreDeporte>
            <nombre>Mark Spitz</nombre>
        </deporte>
    </deportista>
</deportistas>
